# This file is used for automated tests with Travis CI : travis-ci.org
# based on the template version 1
# the templates are availables in the documentation on http://docs.domogik.org/domogik/dev/en/package_development/plugins/tests/travis_templates.html

# TODO
# - python 2.7 / 3
# - mysql and postgres for domogik
# - after success and similar => dashboard : http://about.travis-ci.org/fr/docs/user/status-images/
#                                            http://about.travis-ci.org/docs/user/ci-environment/
# - notifications (irc notamment) : http://about.travis-ci.org/fr/docs/user/build-configuration/
#    notifications:
#       on_success: never
#       on_failure: always
# - dashboard :
#   - projet
#   - branche domogik
#   - branche plugin (ou composant)
#   - version python
#   - base
#   - date
#   - commit
#   - status
#   - status
# DOC : ------------------------------------------------------------------------ 
# - unit test : renvoyer un code retour du py != 0 si on a un échec
# - optimisation : utiliser un .sh dans le repo (plus facilement adaptable). Utiliser le shebang bash + -e : cf https://groups.google.com/forum/#!topic/travis-ci/JtC4WiCMA0w
# - comment gerer les branches ? un yaml dans master suffit ? tester sur depot dmg
#-------------------------------------------------------------------------------
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=0.4-candidate
  DMG_PLUGIN=velbus
install:
  - which python
  - ls -l $(which python)
  - ls -l /usr/bin/python*
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - ~/domogik/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - ~/domogik/src/domogik/tests/travis/travis-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-plugin.sh 
  - ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR
after_script: 
  - ~/domogik/src/domogik/tests/travis/travis-after.sh
notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: always

